services:
  bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "<api-id>"
      TELEGRAM_API_HASH: "<api-hash>"
    networks:
      - music163bot

  bot:
    image: ghcr.io/liuran001/music163bot-go
    volumes:
      - ./config.ini:/app/config.ini
      - ./cache:/app/cache
      - ./log:/app/log
    depends_on:
      bot-api:
        condition: service_started
    networks:
      - music163bot

networks:
  music163bot:
